{% set name = "libcxx-testing" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: .

build:
  number: 0
  skip: true  # [not (osx and python_impl == 'cpython')]
  script:
    echo "works!"

requirements:
  run:
    - python
    - pybind11
    - {{ compiler('cxx') }}
    - make
    - pip
    - boost-cpp

test:
  files:
    - pybind11_exception_rtti_test
    - boost_example.cpp

about:
  home: https://github.com/conda-forge/libcxx-testing-feedstock
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: pybind11_exception_rtti_test/README.md
  summary: 'a test of RTTI for exception passing in C++ and pybind11'

extra:
  recipe-maintainers:
    - beckermr
